import "server-only";

import { MAX_RECEIVED_ATTACHMENT_DOWNLOAD_BYTES } from "@/domain/mail/received-attachment";
import { id } from "@/domain/shared/brand";

const securityOptions = [
  { label: "TLS (recommended)", value: "tls" },
  { label: "STARTTLS", value: "starttls" },
] as const;
const optionalSieveSecurityOptions = [
  { label: "Disabled", value: "" },
  ...securityOptions,
] as const;

export const imapSmtpManifest = {
  capabilities: {
    maxAttachmentBytes: 18 * 1024 * 1024,
    maxAttachmentDownloadBytes: MAX_RECEIVED_ATTACHMENT_DOWNLOAD_BYTES,
    supportsAttachmentDownload: true,
    supportsDrafts: false,
    supportsPasswordChange: false,
    supportsProfileSettings: false,
    supportsPush: false,
    supportsServerSearch: true,
    supportsThreads: true,
    supportsTwoFactorAuthentication: false,
  },
  description: "Connect Hostinger, cPanel, Zoho and other standard IMAP/SMTP services.",
  fields: [
    {
      defaultValue: "imap.example.com",
      help: "Public hostname from your provider's incoming-mail settings.",
      kind: "text",
      label: "IMAP host",
      name: "imapHost",
      placeholder: "imap.example.com",
      required: true,
      scope: "service",
      secret: false,
    },
    {
      defaultValue: "993",
      kind: "text",
      label: "IMAP port",
      name: "imapPort",
      required: true,
      scope: "service",
      secret: false,
    },
    {
      defaultValue: "tls",
      kind: "select",
      label: "IMAP security",
      name: "imapSecurity",
      options: securityOptions,
      required: true,
      scope: "service",
      secret: false,
    },
    {
      defaultValue: "",
      help: "Optional RFC 5804 hostname. Leave blank to disable mail rules.",
      kind: "text",
      label: "ManageSieve host",
      name: "manageSieveHost",
      placeholder: "sieve.example.com",
      required: false,
      scope: "service",
      secret: false,
    },
    {
      defaultValue: "",
      help: "Usually 4190. Required when a ManageSieve host is set.",
      kind: "text",
      label: "ManageSieve port",
      name: "manageSievePort",
      placeholder: "4190",
      required: false,
      scope: "service",
      secret: false,
    },
    {
      defaultValue: "",
      help: "Use TLS or STARTTLS; unencrypted ManageSieve is never allowed.",
      kind: "select",
      label: "ManageSieve security",
      name: "manageSieveSecurity",
      options: optionalSieveSecurityOptions,
      required: false,
      scope: "service",
      secret: false,
    },
    {
      defaultValue: "smtp.example.com",
      help: "Public hostname from your provider's outgoing-mail settings.",
      kind: "text",
      label: "SMTP host",
      name: "smtpHost",
      placeholder: "smtp.example.com",
      required: true,
      scope: "service",
      secret: false,
    },
    {
      defaultValue: "465",
      kind: "text",
      label: "SMTP port",
      name: "smtpPort",
      required: true,
      scope: "service",
      secret: false,
    },
    {
      defaultValue: "0",
      help:
        "Optional message-size ceiling in bytes. Use 0 to require the " +
        "server's SMTP SIZE limit; attachments stay disabled if neither " +
        "source supplies a verifiable limit.",
      kind: "text",
      label: "SMTP maximum message bytes",
      name: "smtpMaxMessageBytes",
      placeholder: "0",
      required: false,
      scope: "service",
      secret: false,
    },
    {
      defaultValue: "tls",
      kind: "select",
      label: "SMTP security",
      name: "smtpSecurity",
      options: securityOptions,
      required: true,
      scope: "service",
      secret: false,
    },
    {
      autocomplete: "username",
      kind: "email",
      label: "Email address",
      name: "email",
      placeholder: "you@example.com",
      required: true,
      scope: "member",
      secret: false,
    },
    {
      autocomplete: "current-password",
      kind: "password",
      label: "Password or app password",
      name: "password",
      required: true,
      scope: "member",
      secret: true,
    },
  ],
  id: id.provider("imap-smtp"),
  name: "Standard IMAP + SMTP",
} as const;
