export const MAIL_USER_IDEMPOTENCY_TTL_MS = 24 * 60 * 60 * 1_000;
export const MAX_MAIL_USER_IDEMPOTENCY_ENTRIES = 512;
export const MAIL_USER_IDEMPOTENCY_SHARED_RETRIES = 10;
export const MAIL_USER_IDEMPOTENCY_POLL_MS = 50;
export const MAIL_USER_IDEMPOTENCY_WAIT_MS = 90_000;
export const MAIL_USER_IDEMPOTENCY_OWNER_MS = 2 * 60 * 1_000;
