LogTime yes
LogClean no
LogVerbose no
ExtendedDetectionInfo no
DatabaseDirectory /var/lib/clamav

TCPSocket 3310
TCPAddr 0.0.0.0
LocalSocket /tmp/clamd.sock
LocalSocketMode 660
FixStaleSocket yes
EnableShutdownCommand no
EnableStatsCommand no
EnableVersionCommand no
MaxConnectionQueueLength 16
StreamMaxLength 50M
MaxThreads 4
ReadTimeout 60
CommandReadTimeout 5
SendBufTimeout 500
MaxQueue 16
IdleTimeout 60

User clamav
Foreground yes
LeaveTemporaryFiles no
GenerateMetadataJson no
AllowAllMatchScan no
HeuristicAlerts yes
HeuristicScanPrecedence yes
AlertEncrypted yes
ScanPartialMessages no
ScanArchive yes

MaxScanTime 90000
MaxScanSize 100M
MaxFileSize 50M
MaxRecursion 8
MaxFiles 1000
MaxEmbeddedPE 20M
MaxHTMLNormalize 20M
MaxHTMLNoTags 4M
MaxScriptNormalize 8M
MaxZipTypeRcg 1M
MaxPartitions 16
MaxIconsPE 100
MaxRecHWP3 8
PCREMatchLimit 50000
PCRERecMatchLimit 1000
PCREMaxFileSize 20M
AlertExceedsMax yes
BytecodeTimeout 5000
