import type { ComposerViewModel } from "@/presentation/features/mail-workspace/mail-workspace.view-model";
import { createComposerAttachmentViewModel } from "@/presentation/features/mail-workspace/composer-attachment.view-model";
import type { useComposerModel } from "@/presentation/features/mail-workspace/hooks/use-composer-model";

export const createComposerViewModel = (
  composer: ReturnType<typeof useComposerModel>,
): ComposerViewModel => ({
  attachments: composer.attachments.map((attachment) =>
    createComposerAttachmentViewModel(
      attachment,
      composer.removeAttachment,
      composer.retryAttachment,
    ),
  ),
  attachmentInput: composer.onAttachmentInput,
  attachmentCapabilityUnavailable: composer.attachmentCapabilityUnavailable,
  bcc: composer.bcc,
  bccInput: composer.onBccInput,
  body: {
    cancelPlainMode: composer.body.cancelPlainMode,
    confirmPlainMode: composer.body.confirmPlainMode,
    editorVersion: composer.body.editorVersion,
    html: composer.body.html,
    isPlainModeWarningOpen: composer.body.isPlainModeWarningOpen,
    mode: composer.body.mode,
    onPlainDrop: composer.body.onPlainDrop,
    onPlainInput: composer.body.onPlainInput,
    onPlainPaste: composer.body.onPlainPaste,
    onRichChange: composer.body.onRichChange,
    onRichInitialize: composer.body.onRichInitialize,
    onToggleMode: composer.body.onToggleMode,
    onWarningKeyDown: composer.body.onWarningKeyDown,
    plainTransferStatus: composer.body.plainTransferStatus,
    signature: composer.signatures.configuration,
    signatureAnnouncement: composer.signatures.announcement,
    signatureDetached: composer.signatures.isDetached,
    text: composer.body.text,
  },
  cc: composer.cc,
  ccInput: composer.onCcInput,
  closeConfirmation: {
    isOpen: composer.closeConfirmationOpen,
    onCancel: composer.onCancelClose,
    onConfirm: composer.onConfirmClose,
  },
  discardConfirmation: {
    isOpen: composer.discardConfirmationOpen,
    onCancel: composer.onCancelDiscard,
    onConfirm: composer.onConfirmDiscard,
  },
  draft: {
    canDiscard: composer.draft.canDiscard,
    canEdit: composer.draft.canEdit,
    canSave: composer.draft.canSave,
    canSend: composer.draft.canSend,
    enabled: composer.draft.enabled,
    error: composer.draft.error,
    loadFailed: composer.draft.loadFailed,
    onReload: composer.draft.reload,
    onRequestDiscard: composer.onRequestDiscard,
    onRetry: composer.draft.retry,
    onSave: composer.draft.save,
    phase: composer.draft.phase,
    requiresRecovery: composer.draft.requiresRecovery,
    sendBlockedMessage: composer.draft.sendBlockedMessage,
  },
  error: composer.error,
  focusBody: Boolean(composer.to),
  isAttachmentCapabilityRefreshing: composer.isAttachmentCapabilityRefreshing,
  isBusy: composer.isBusy,
  isOpen: composer.isOpen,
  isSending: composer.isSending,
  isUploading: composer.isUploading,
  maxAttachmentBytes: composer.maxAttachmentBytes,
  onClose: composer.close,
  onRetryAttachmentCapability: composer.onRetryAttachmentCapability,
  onToggleBcc: composer.onToggleBcc,
  onToggleCc: composer.onToggleCc,
  onSubmit: composer.onSubmit,
  showBcc: composer.showBcc,
  showCc: composer.showCc,
  subject: composer.subject,
  subjectInput: composer.onSubjectInput,
  to: composer.to,
  toInput: composer.onToInput,
  title: composer.title,
});
