import type { ComposerViewModel } from "@/presentation/features/mail-workspace/mail-workspace.view-model";
import { createComposerAttachmentViewModel } from "@/presentation/features/mail-workspace/composer-attachment.view-model";
import type { useComposerModel } from "@/presentation/features/mail-workspace/hooks/use-composer-model";

export const createComposerViewModel = (
  composer: ReturnType<typeof useComposerModel>,
): ComposerViewModel => ({
  attachments: composer.attachments.map((attachment) =>
    createComposerAttachmentViewModel(
      attachment,
      composer.removeAttachment,
      composer.retryAttachment,
    ),
  ),
  attachmentInput: composer.onAttachmentInput,
  attachmentCapabilityUnavailable: composer.attachmentCapabilityUnavailable,
  bcc: composer.bcc,
  bccInput: composer.onBccInput,
  body: {
    cancelPlainMode: composer.body.cancelPlainMode,
    confirmPlainMode: composer.body.confirmPlainMode,
    editorVersion: composer.body.editorVersion,
    html: composer.body.html,
    isPlainModeWarningOpen: composer.body.isPlainModeWarningOpen,
    mode: composer.body.mode,
    onPlainDrop: composer.body.onPlainDrop,
    onPlainInput: composer.body.onPlainInput,
    onPlainPaste: composer.body.onPlainPaste,
    onRichChange: composer.body.onRichChange,
    onToggleMode: composer.body.onToggleMode,
    onWarningKeyDown: composer.body.onWarningKeyDown,
    plainTransferStatus: composer.body.plainTransferStatus,
    signature: composer.signatures.configuration,
    signatureAnnouncement: composer.signatures.announcement,
    signatureDetached: composer.signatures.isDetached,
    text: composer.body.text,
  },
  cc: composer.cc,
  ccInput: composer.onCcInput,
  error: composer.error,
  focusBody: Boolean(composer.to),
  isAttachmentCapabilityRefreshing: composer.isAttachmentCapabilityRefreshing,
  isOpen: composer.isOpen,
  isSending: composer.isSending,
  isUploading: composer.isUploading,
  maxAttachmentBytes: composer.maxAttachmentBytes,
  onClose: composer.close,
  onRetryAttachmentCapability: composer.onRetryAttachmentCapability,
  onToggleBcc: composer.onToggleBcc,
  onToggleCc: composer.onToggleCc,
  onSubmit: composer.onSubmit,
  showBcc: composer.showBcc,
  showCc: composer.showCc,
  subject: composer.subject,
  subjectInput: composer.onSubjectInput,
  to: composer.to,
  toInput: composer.onToInput,
  title: composer.title,
});
