import { Clock3, X } from "lucide-react";
import type { MailSnoozeViewModel } from "@/presentation/features/mail-workspace/mail-snooze.view-model";

export const MailSnoozeDialogView = ({ snooze }: { readonly snooze: MailSnoozeViewModel }) =>
  snooze.dialog.isOpen ? <div aria-describedby="mail-snooze-description" aria-labelledby="mail-snooze-title" aria-modal="true" className="fixed inset-0 z-[85] grid place-items-center bg-slate-950/55 p-3 backdrop-blur-sm sm:p-6" id="mail-snooze-dialog" role="dialog" tabIndex={-1}>
    <button aria-label="Cancel snooze" className="absolute inset-0 cursor-default" disabled={snooze.dialog.isBusy} onClick={snooze.dialog.onCancel} tabIndex={-1} type="button" />
    <section className="relative w-full max-w-md rounded-3xl border border-white/40 bg-white p-5 shadow-2xl sm:p-6">
      <header className="flex items-start gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-indigo-100 text-indigo-700"><Clock3 aria-hidden size={21} /></span><div className="min-w-0 flex-1"><h2 className="font-extrabold text-slate-900" id="mail-snooze-title">{snooze.dialog.targetLabel}</h2><p className="text-xs text-slate-600" id="mail-snooze-description">The provider will hide the message and restore it at this time.</p></div><button aria-label="Cancel snooze" className="grid size-9 place-items-center rounded-xl text-slate-500 hover:bg-slate-100 disabled:opacity-50" disabled={snooze.dialog.isBusy} onClick={snooze.dialog.onCancel} type="button"><X aria-hidden size={18} /></button></header>
      <div className="mt-5 grid gap-2 sm:grid-cols-3">{snooze.dialog.presets.map((preset, index) => <button className="min-h-12 rounded-xl border border-slate-200 px-2 py-2 text-left hover:border-indigo-300 hover:bg-indigo-50 focus-visible:outline-2 focus-visible:outline-indigo-600 disabled:opacity-50" data-snooze-initial-focus={index === 0 ? true : undefined} disabled={snooze.dialog.isBusy} key={preset.id} onClick={() => snooze.dialog.onPreset(preset.value)} type="button"><span className="block text-xs font-bold text-slate-800">{preset.label}</span><span className="block text-[10px] text-slate-500">{preset.resolved}</span></button>)}</div>
      <label className="mt-5 block text-xs font-bold text-slate-700">Custom date and time<input className="mt-2 h-11 w-full rounded-xl border border-slate-300 px-3 text-sm outline-none focus:border-indigo-600 focus:ring-2 focus:ring-indigo-100" disabled={snooze.dialog.isBusy} max={snooze.dialog.maximum} min={snooze.dialog.minimum} onChange={snooze.dialog.onTimeInput} type="datetime-local" value={snooze.dialog.localTime} /></label>
      <p className="mt-2 text-xs text-slate-500">Time zone: {snooze.dialog.timeZone}. UTC: {snooze.dialog.resolvedUtc ?? "Choose a valid time"}</p>
      {snooze.dialog.error ? <p className="mt-3 rounded-xl bg-rose-50 px-3 py-2 text-xs font-semibold text-rose-700" role="alert">{snooze.dialog.error}</p> : null}
      <div className="mt-5 flex justify-end gap-2"><button className="h-10 rounded-xl px-3 text-sm font-bold text-slate-700 hover:bg-slate-100 disabled:opacity-50" disabled={snooze.dialog.isBusy} onClick={snooze.dialog.onCancel} type="button">Cancel</button><button className="h-10 rounded-xl bg-indigo-700 px-4 text-sm font-bold text-white hover:bg-indigo-800 disabled:opacity-50" disabled={snooze.dialog.isBusy || !snooze.dialog.resolvedUtc} onClick={snooze.dialog.onConfirm} type="button">{snooze.dialog.isBusy ? "Saving…" : snooze.dialog.confirmLabel}</button></div>
    </section>
  </div> : null;
