import { Clock3, RefreshCw, RotateCcw, X } from "lucide-react";
import type { MailSnoozeViewModel } from "@/presentation/features/mail-workspace/mail-snooze.view-model";

export const SnoozedManagerView = ({ snooze }: { readonly snooze: MailSnoozeViewModel }) =>
  snooze.manager.isOpen ? <div aria-labelledby="snoozed-manager-title" aria-modal="true" className="fixed inset-0 z-[80] grid place-items-center bg-slate-950/55 p-3 backdrop-blur-sm sm:p-6" id="snoozed-manager-dialog" role="dialog" tabIndex={-1}>
    <button aria-label="Close Snoozed" className="absolute inset-0 cursor-default" disabled={snooze.isBusy} onClick={snooze.manager.close} tabIndex={-1} type="button" />
    <section className="relative flex max-h-[90dvh] w-full max-w-xl flex-col overflow-hidden rounded-3xl bg-white shadow-2xl">
      <header className="flex items-center gap-3 border-b border-slate-200 p-5"><span className="grid size-10 place-items-center rounded-xl bg-indigo-100 text-indigo-700"><Clock3 aria-hidden size={20} /></span><div className="min-w-0 flex-1"><h2 className="font-extrabold text-slate-900" id="snoozed-manager-title">Snoozed</h2><p className="text-xs text-slate-500">Messages scheduled to return</p></div><button aria-label="Close Snoozed" className="grid size-10 place-items-center rounded-xl hover:bg-slate-100 disabled:opacity-50" data-snoozed-manager-initial-focus disabled={snooze.isBusy} onClick={snooze.manager.close} type="button"><X aria-hidden size={18} /></button></header>
      <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5">
        {snooze.error ? <p className="mb-3 rounded-xl bg-rose-50 p-3 text-sm text-rose-700" role="alert">{snooze.error}</p> : null}
        {snooze.isLoading ? <p className="py-8 text-center text-sm text-slate-500" role="status">Loading snoozed messages…</p> : null}
        {!snooze.isLoading && !snooze.jobs.length ? <p className="py-10 text-center text-sm text-slate-500">No snoozed messages.</p> : null}
        <ol className="space-y-3">{snooze.jobs.map((job) => <li className="rounded-2xl border border-slate-200 p-4" key={job.id}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-bold text-slate-900">{job.subject || "(No subject)"}</p><p className="truncate text-xs text-slate-500">{job.from.join(", ") || "Unknown sender"}</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold text-slate-600">{job.statusLabel}</span></div><p className="mt-2 text-xs text-slate-600">Returns {job.wakeLabel}</p>{job.lastError ? <p className="mt-2 text-xs text-rose-700" role="alert">{job.lastError}</p> : null}<div className="mt-3 flex flex-wrap gap-2"><button className="inline-flex min-h-10 items-center gap-1 rounded-xl border border-slate-200 px-3 text-xs font-bold hover:bg-slate-50 disabled:opacity-50" disabled={snooze.isBusy} onClick={() => snooze.onRestore(job.id)} type="button"><RotateCcw aria-hidden size={14} />Restore now</button><button className="inline-flex min-h-10 items-center gap-1 rounded-xl border border-slate-200 px-3 text-xs font-bold hover:bg-slate-50 disabled:opacity-50" disabled={snooze.isBusy} onClick={() => snooze.onReschedule(job)} type="button"><Clock3 aria-hidden size={14} />Change time</button>{job.status === "failed" || job.status === "needs-auth" ? <button className="inline-flex min-h-10 items-center gap-1 rounded-xl bg-indigo-50 px-3 text-xs font-bold text-indigo-700 disabled:opacity-50" disabled={snooze.isBusy} onClick={() => snooze.onRetry(job.id)} type="button"><RefreshCw aria-hidden size={14} />Retry</button> : null}</div></li>)}</ol>
      </div>
    </section>
  </div> : null;
